services:
  - docker

env:
  - NAME=jat001/archisteamfarm

install: true

before_script:
  - REL=$(curl https://api.github.com/repos/JustArchi/ArchiSteamFarm/releases/latest)
  - VER=$(echo "$REL" | jq -r '.tag_name')

  - curl -f "https://index.docker.io/v1/repositories/$NAME/tags/$VER" && travis_terminate 0
  - docker login -u=jat001 -p="$DOCKER_PASSWD"

script:
  - curl -Lo ASF.exe "$(echo '$REL' | jq -r '.assets[] | select(.name == "ASF.exe").browser_download_url')"

  - docker build -t "$NAME:$VER" --build-arg "VER=$VER" .
  - docker tag "$NAME:$VER" "$NAME:latest"

  - docker push "$NAME:$VER"
  - docker push "$NAME:latest"
